language: go
go: 1.12

# workarround to successful build a forked version (import path set to the github.com/gtalent/tendb)
before_install:
  - mkdir -p $HOME/gopath/src/github.com/gtalent/tendb
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/gtalent/tendb/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/gtalent/tendb
  - cd $HOME/gopath/src/github.com/gtalent/tendb

install:
  - go get github.com/gtalent/tendb/exec
  - go get github.com/gtalent/tendb/assets_generate

script:
  - make generate build
